### ISSUE TITLE
conv1x1-conv3x3 mid_planes

### ISSUE THREAD

**Issue by Ken1256** [icandle/EFDN#3]
EDBB depth_multiplier preset = out_planes * inp_planes  > mid_planes = out_planes * depth_multiplierare right?
ECBSR depth_multiplier preset = 2.0

https://github.com/xindongzhang/ECBSR/blob/main/models/ecbsr.py

**Comment by icandle** [comment]
It should be 2.0 as ECB. The preset is wrong and not used in training.
