### ISSUE TITLE
有关论文内容的几个疑问

### ISSUE THREAD

**Issue by zizixixi** [icandle/EFDN#5]
您好！您的这篇加强边缘特征的图像超分文章对我很有启发，但是我在阅读的过程中有几点疑问，想向您请教一下。
1.损失函数的权重确定
![image](https://user-images.githubusercontent.com/107998623/175021385-4cd013f3-3bbb-4e13-aae5-64a968ac1bfd.png)
请问这里scaled parameters Sx,Sy,Sl是指什么？是EDBB中对应soblex, sobley, laplace3个分支conv1的卷积核参数吗？
还有normalized weights of s又是指什么？以及这个normalized weights是怎么计算的？
2. 梯度方差计算公式
![image](https://user-images.githubusercontent.com/107998623/175020829-27c8d2de-3936-4720-91fc-a9535426a1c1.png)
按照我以往对方差计算的理解，我认为这里分子上应该有平方，请问您这里没有进行平方运算是如何考虑的？

感谢您在百忙之中阅读我的问题，期待您的回复！谢谢！

**Comment by icandle** [comment]
1.s是最后一层卷积EDBB使用switch_gv的scaling的参数（卷积核参数是固定的），归一化就是根据s求得每个权重所占的比例（将其看作每种滤波对最后一层重建的贡献程度）。在最后计算\lambda_x时将这个比例再乘上一个系数，比如1e-3，作为损失的系数。
2.是应该有平方的。。。。。。打错了，虽然很不应该。
感谢您对我的工作的支持！
