### ISSUE TITLE
2x upscaling

### ISSUE THREAD

**Issue by fehimebetul** [icandle/EFDN#8]
What parameter do I need to change for 2x upscaling?

**Comment by icandle** [comment]
Only the scale factor. But you may need to retrain the EFDN x2 based on x4 model.

**Comment by fehimebetul** [comment]
You have stated in your paper that you have tried 2x, do you already have a model?

**Comment by icandle** [comment]
Yeah, but we only backed up the competition results, the experiment was done on a leased server. Sorry.

**Comment by icandle** [comment]
We may replenish this part in the future.
